import React from "react";
import Head from "next/head";
import Link from "next/link";
import styles from "./Header.module.scss";

const Header = () => {
  return (
    <div className={styles.header}>
      <Head>
        <title>portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.header_nav}>
        <Link href="/">
          <span className={styles.logo_name}>Kay</span>
        </Link>

        <Link href="/pages/contact">
          <span className={styles.contact_nav}>Contact me</span>
        </Link>
      </nav>
    </div>
  );
};

export default Header;
